USE ContactCare
GO
--CREATE LOGIN
CREATE LOGIN [New_Login] 
	WITH PASSWORD=N'N3wU$3r' 
	MUST_CHANGE, 
	DEFAULT_DATABASE=GuestHouse2020, 
	CHECK_EXPIRATION=ON, 
	CHECK_POLICY=ON
GO

--CREATE ROLE
CREATE ROLE Worker;
GO

--CREATE USER
CREATE USER Dale FOR LOGIN [New_Login] 
GO

--ADD USER TO ROLE
ALTER ROLE [Worker] ADD MEMBER [Dale]
GO

--ADD ACCESS TO VIEWS
GRANT SELECT ON dbo.V_Point_Contact TO [Worker]
GRANT SELECT ON dbo.V_Point_Contact TO [Worker]
GO